# Generated by Django 4.2.10 on 2026-01-16 03:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_product_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(help_text='Título breve de la reseña', max_length=200)),
                ('comment', models.TextField(help_text='Cuéntanos tu experiencia con el producto')),
                ('image', models.ImageField(blank=True, help_text='Foto opcional del producto', null=True, upload_to='reviews/')),
                ('is_approved', models.BooleanField(default=True, help_text='¿La reseña está aprobada para mostrarse?')),
                ('verified_purchase', models.BooleanField(default=False, help_text='¿El usuario compró este producto?')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Cantidad de usuarios que encontraron útil esta reseña')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
